### ISSUE TITLE
Support go_ibm_db driver with UBI 9 and openssl 3.0

### ISSUE THREAD

**Issue by asghar3** [ibmdb/go_ibm_db#225]
**Is your feature request related to a problem? Please describe.**
Support go_ibm_db driver with ubi9 where Openssl is 3.0

**Describe the solution you'd like**
We are unable to consume this golang driver in ubi9 where it's openssl 3.0.
We run into issues with libs required by the db2 cli driver in ubi 9 

/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: warning: libcrypt.so.1, needed by /clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /clidriver/lib/libdb2.so: undefined reference to `crypt_r@GLIBC_2.2.5'
collect2: error: ld returned 1 exit status

**Describe alternatives you've considered**
Keep using ubi 8 for now where db2 cli driver works fine in openssl 1.1

**Additional context**

**Comment by asghar3** [comment]
@bimalkjha I have submitted the idea.
I have hoping given go_ibm_db is the consumers of cli driver you guys will be able to help point me the support docs for the cli driver.
I will try to provide the ubi8 example with using openssl1.1 and clidriver.
Thanks

**Comment by bimalkjha** [comment]
@asghar3 Documentation for CLI driver is part of Db2 documentation. You can start here: https://www.ibm.com/docs/en/db2/11.5?topic=applications-cli-odbc
For SSL connection and how to configure it, you can start from this doc: https://www.ibm.com/docs/en/db2/11.5?topic=ctsidc-configuring-tls-support-in-non-java-db2-clients
Also, refer other links on above doc. 
I do not see any reference about use of openssl1.1 with clidriver. Thanks.

**Comment by bimalkjha** [comment]
@asghar3 To fix the GLIBC_2.2.5 error, you need to install libxcrypt-compat library. Try to install it using `sudo yum install libxcrypt-compat` command. Thanks.

**Comment by bimalkjha** [comment]
@asghar3 Hope you have installed the required OS package which solved the issue. Hence, closing the issue now. If you still have any problem, feel free to comment here. Thanks.

**Comment by asghar3** [comment]
I didn't get the chance to try installing libxcrypt-compat and see if that helps.
I will give a try and come back if this doesn't help. Thanks
