### ISSUE TITLE
SqloCosClient::SqloCosClient_toString(unsigned long, char*)

### ISSUE THREAD

**Issue by dorudumitru-hh** [ibmdb/go_ibm_db#177]
- os Version: Red Hat Enterprise Linux 8.6
- cli-driver Version: 11.5.7
- Db2 Server Version:
- go Version: 1.18.5
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/doru.dumitru/.cache/go-build"
GOENV="/home/doru.dumitru/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/doru.dumitru/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/doru.dumitru/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2703712586=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

It's mandatory for our project to use driver v11.5.7 so I downloaded it from IBM Fix Central.
When trying to run or build:
<code>/home/doru.dumitru/Projects/ibm/watson-translate-go/clidriver/lib/libdb2.so: undefined reference to `SqloCosClient::SqloCosClient_toString(unsigned long, char*)'
collect2: error: ld returned 1 exit status</code>

**Comment by vmathur12** [comment]
Hi @dorudumitru-hh 
Can you please try installing and setting up the driver using Readme?
Because I see CGO_CFLAGS, CGO_LDFLAGS are not correct.
Thanks

**Comment by dorudumitru-hh** [comment]
They are set every time I try to run or build the app by Makefile. It works fine with 11.5.6.

**Comment by dorudumitru-hh** [comment]
Just to be safe, here is go env again with the env variables set. I get the same error.
<details><summary><code>go env</code></summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/doru.dumitru/.cache/go-build"
GOENV="/home/doru.dumitru/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/doru.dumitru/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/doru.dumitru/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-I/home/doru.dumitru/Projects/ibm/watson-translate-go/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/doru.dumitru/Projects/ibm/watson-translate-go/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3642429401=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by vmathur12** [comment]
Hi @dorudumitru-hh 
Please download the clidriver from the following special build link

https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_13966_148677_DSClients-linuxx64-odbc_cli-11.5.7.0-FP000%3A560168888922865664&includeSupersedes=0

Let me know if you are facing this issue again.
Thanks

**Comment by dorudumitru-hh** [comment]
Hi @vmathur12 
Everything works fine. Thanks a lot.

**Comment by vmathur12** [comment]
Special Build:
https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_26260_270811_DSClients-linuxx64-dsdriver-11.5.8.0-FP000%3A510049537921833024&includeSupersedes=0
